# Generated by Django 4.1.3 on 2022-11-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'No binario')], default='F', max_length=2)),
                ('opinion', models.CharField(choices=[('EXC', 'Excelente'), ('MB', 'Muy bueno'), ('B', 'Bueno'), ('REG', 'Regular'), ('M', 'Malisimo')], default='B', max_length=3)),
                ('resenia', models.TextField(max_length=500)),
                ('edades', models.IntegerField(max_length=3)),
                ('estudios', models.CharField(choices=[('PI', 'Primario incompleto'), ('PC', 'Primario completo'), ('SI', 'Secundario incompleto'), ('SC', 'Secundario completo'), ('UI', 'Universitario incompleto'), ('UC', 'Universitario completo'), ('PGR', 'Postgrado')], default='SC', max_length=3)),
            ],
        ),
    ]
