# Generated by Django 4.1.3 on 2022-11-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterselling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='producto',
            field=models.IntegerField(default=1),
        ),
    ]
