# Generated by Django 4.1 on 2022-11-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterselling', '0003_alter_encuesta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='edades',
            field=models.IntegerField(),
        ),
    ]
