# Generated by Django 4.1.3 on 2022-12-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afterselling', '0003_alter_encuesta_edades_alter_encuesta_id'),
        ('afterselling', '0004_alter_encuesta_edades'),
    ]

    operations = [
    ]
