# Generated by Django 4.1.3 on 2022-12-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_servicio_tem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('datos', models.FileField(upload_to='servicios/datos')),
            ],
            options={
                'verbose_name': 'datos',
                'verbose_name_plural': 'datos',
            },
        ),
    ]
