# Generated by Django 4.1.3 on 2022-12-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comentario'),
        ('blog', '0003_post_content_comentario'),
    ]

    operations = [
    ]
